import { profile } from "@/content/profile";

/** The 3D contribution skyline generated by the "GitHub Profile 3D Contrib"
 *  Action (.github/workflows/github-profile-3d-contrib.yml) — it commits a
 *  fresh SVG to this repo daily. Pulled straight from GitHub's raw CDN, so the
 *  image self-updates without a site redeploy. */
const SKYLINE_URL = `https://raw.githubusercontent.com/${profile.githubUsername}/myPortfolio/main/profile-3d-contrib/profile-night-view.svg`;

export default function ContributionCalendar() {
  return (
    <section aria-labelledby="contributions-heading" className="mt-10">
      <h3
        id="contributions-heading"
        className="mb-4 text-sm font-semibold uppercase tracking-[0.1em] text-muted"
      >
        Contributions
      </h3>

      <a
        href={`https://github.com/${profile.githubUsername}`}
        target="_blank"
        rel="noreferrer"
        className="block overflow-hidden rounded-2xl border border-white/[0.08] bg-white/5 transition-colors duration-200 hover:border-white/20"
      >
        <img
          src={SKYLINE_URL}
          alt={`3D visualization of ${profile.githubUsername}'s GitHub commit history over the last year, with a breakdown of commits, issues, pull requests, reviews and repositories, and languages used`}
          loading="lazy"
          className="w-full"
        />
      </a>
    </section>
  );
}
