import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Wrangler's bundle scratch directory.
    ".wrangler/**",
    // Generated by `wrangler types` from wrangler.jsonc. Ten thousand lines of
    // runtime typings that nobody edits by hand.
    "worker-configuration.d.ts",
  ]),
]);

export default eslintConfig;
