/**
 * The whole server side of this site.
 *
 * Everything except /api/visitors is a file in out/, generated by
 * `next build` (output: "export") and served straight from Cloudflare Workers
 * Static Assets. The visitor counter is the one genuinely runtime feature —
 * it needs the Upstash token, which can never reach the browser.
 *
 * Request routing:
 *   /api/visitors  ->  Upstash Redis over its REST API
 *   anything else  ->  env.ASSETS.fetch(request)
 */

interface Env {
  /** Workers Static Assets binding — serves out/ (see wrangler.jsonc). */
  ASSETS: { fetch(request: Request): Promise<Response> };
  UPSTASH_REDIS_REST_URL: string;
  UPSTASH_REDIS_REST_TOKEN: string;
}

/** Same key the Next route used, so the existing count carries over. */
const KEY = "portfolio_visitor_count";

/** A hang is worse than a failure: a failure shows the fallback immediately. */
const TIMEOUT_MS = 5_000;

/** The response shape lib/fetch-json.ts defines and the frontend expects:
 *  { ok: true, data: { count } } | { ok: false, error, stale: true }.
 *
 *  Both go out as HTTP 200 — same as the Next route did. A degraded counter is
 *  not an error the visitor should see, and scripts/check-apis.ts asserts 200
 *  for exactly that reason. Unexpected *requests* still get real status codes
 *  (405 below); only upstream degradation is flattened into ok: false. */
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      // Never cache a live counter, at the edge or in the browser.
      "cache-control": "no-store",
    },
  });

const fail = (error: unknown) =>
  json({
    ok: false,
    error: error instanceof Error ? error.message : "Unknown error",
    stale: true,
  });

async function visitors(request: Request, env: Env): Promise<Response> {
  // POST counts this browser once (the localStorage dedupe lives in
  // components/sections/VisitorCounter.tsx); everything else just reads.
  if (request.method === "POST") {
    return call("incr", env);
  }
  if (request.method === "GET" || request.method === "HEAD") {
    return call("get", env);
  }
  return json({ ok: false, error: "Method not allowed", stale: true }, 405);
}

async function call(command: "get" | "incr", env: Env): Promise<Response> {
  const { UPSTASH_REDIS_REST_URL: url, UPSTASH_REDIS_REST_TOKEN: token } = env;
  if (!url || !token) {
    return fail(new Error("UPSTASH_REDIS_REST_URL/TOKEN not set"));
  }

  try {
    const res = await fetch(`${url}/${command}/${KEY}`, {
      headers: { Authorization: `Bearer ${token}`, Accept: "application/json" },
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
    if (!res.ok) {
      return fail(new Error(`Upstash returned ${res.status}`));
    }
    const { result } = (await res.json()) as { result: number | string | null };
    return json({ ok: true, data: { count: Number(result ?? 0) } });
  } catch (error) {
    return fail(error);
  }
}

const handler = {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Exact match only: no prefix, no trailing slash, so no other path can
    // reach the Upstash credentials.
    if (new URL(request.url).pathname === "/api/visitors") {
      return visitors(request, env);
    }
    return env.ASSETS.fetch(request);
  },
};

export default handler;
