/**
 * The whole server side of this site.
 *
 * Everything that is not listed in ROUTES below is a file in out/, generated by
 * `next build` (output: "export") and served straight from Cloudflare Workers
 * Static Assets. The four stats endpoints (/api/github and friends) are in that
 * category — they are baked into the export at build time and never run here.
 *
 * What genuinely needs a server:
 *
 *   POST/GET /api/visitors          -> the site-wide visitor counter
 *   POST     /api/blog-views/:slug  -> record one read of a post
 *   GET      /api/blog-views        -> every post's count, for /views
 *   POST     /api/contact           -> Turnstile, then D1, then email
 *   POST     /api/newsletter        -> Turnstile, then D1
 *   anything else                   -> env.ASSETS.fetch(request)
 *
 * Storage split: D1 holds rows you will want to read back and export (contact
 * messages, subscribers); KV holds counters and rate-limit windows, which are
 * single integers with a TTL and far more writes than reads of any one key.
 *
 * Every binding is optional at runtime. A missing KV or D1 binding degrades the
 * endpoint that needs it to `{ ok: false }` instead of throwing — which is what
 * lets this file be deployed before the namespaces exist in wrangler.jsonc.
 */

interface Env {
  /** Workers Static Assets binding — serves out/ (see wrangler.jsonc). */
  ASSETS: { fetch(request: Request): Promise<Response> };

  /** Counters, caches and rate-limit windows. Declared in wrangler.jsonc once
   *  the namespace exists; undefined until then. */
  KV?: KVNamespace;
  /** Contact messages and newsletter subscribers. */
  DB?: D1Database;

  /** Server half of the Turnstile pair. When this is absent the token check is
   *  skipped — see verifyTurnstile. */
  TURNSTILE_SECRET_KEY?: string;

  RESEND_API_KEY?: string;
  CONTACT_TO_EMAIL?: string;

  /** Legacy visitor-counter store. Still read when KV is not bound yet, so the
   *  counter keeps working through the migration rather than resetting. */
  UPSTASH_REDIS_REST_URL?: string;
  UPSTASH_REDIS_REST_TOKEN?: string;
}

/** Same key the Next route used, so any existing count carries over. */
const VISITOR_KEY = "portfolio_visitor_count";
const VIEW_PREFIX = "views:";
const RATE_PREFIX = "rate:";

/** A hang is worse than a failure: a failure shows the fallback immediately. */
const TIMEOUT_MS = 5_000;

/** Per-IP budget on the mutating endpoints. Turnstile is the real bot gate;
 *  this is the cheap second layer that also covers anything Turnstile is not
 *  attached to.
 *
 *  ponytail: KV is eventually consistent, so a burst arriving at several edges
 *  at once can slip a few extra requests through. That is an acceptable ceiling
 *  for a portfolio contact form. Move to a Durable Object if it ever needs to
 *  be exact. */
const RATE_LIMIT = 5;
const RATE_WINDOW_S = 60;

/** The response shape lib/fetch-json.ts defines and the frontend expects:
 *  { ok: true, data } | { ok: false, error, stale: true }.
 *
 *  Both go out as HTTP 200 — same as the Next route did. A degraded counter is
 *  not an error the visitor should see, and scripts/check-apis.ts asserts 200
 *  for exactly that reason. Unexpected *requests* still get real status codes
 *  (405, 429 below); only upstream degradation is flattened into ok: false. */
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      // Never cache a live counter, at the edge or in the browser.
      "cache-control": "no-store",
    },
  });

const fail = (error: unknown, status = 200) =>
  json(
    {
      ok: false,
      error: error instanceof Error ? error.message : String(error),
      stale: true,
    },
    status,
  );

/* ------------------------------------------------------------------ guards */

/** Cross-origin writes are refused outright. The frontend and this Worker share
 *  an origin, so a request from anywhere else is either a mistake or an attack;
 *  either way there is nothing to gain by answering it. */
function sameOrigin(request: Request): boolean {
  const origin = request.headers.get("origin");
  // No Origin header at all: a same-origin GET, or a non-browser client. The
  // per-route method check already rejects the shapes that matter.
  if (!origin) return true;
  try {
    return new URL(origin).host === new URL(request.url).host;
  } catch {
    return false;
  }
}

function clientIp(request: Request): string {
  // Set by Cloudflare on every request and not forgeable by the client — unlike
  // X-Forwarded-For, which is.
  return request.headers.get("cf-connecting-ip") ?? "unknown";
}

/** Returns true when the caller is over budget. Fails OPEN: if KV is missing or
 *  erroring, a contact form that still works beats one that refuses everyone. */
async function rateLimited(env: Env, request: Request, bucket: string) {
  if (!env.KV) return false;
  const key = `${RATE_PREFIX}${bucket}:${clientIp(request)}`;
  try {
    const current = Number((await env.KV.get(key)) ?? 0);
    if (current >= RATE_LIMIT) return true;
    await env.KV.put(key, String(current + 1), {
      expirationTtl: RATE_WINDOW_S,
    });
    return false;
  } catch {
    return false;
  }
}

/** Verifies a Turnstile token server-side.
 *
 *  With no secret configured this returns true — the widget is not rendered in
 *  that case either (see components/sections/ContactForm.tsx), so the site is
 *  consistent rather than half-protected. Configure the pair and both halves
 *  switch on together. */
async function verifyTurnstile(env: Env, token: string, ip: string) {
  if (!env.TURNSTILE_SECRET_KEY) return true;
  if (!token) return false;

  try {
    const res = await fetch(
      "https://challenges.cloudflare.com/turnstile/v0/siteverify",
      {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          secret: env.TURNSTILE_SECRET_KEY,
          response: token,
          remoteip: ip,
        }),
        signal: AbortSignal.timeout(TIMEOUT_MS),
      },
    );
    const result = (await res.json()) as { success?: boolean };
    return result.success === true;
  } catch {
    // Turnstile unreachable. Fail CLOSED here: this is the anti-abuse gate, and
    // an outage must not turn the form into an open relay.
    return false;
  }
}

/** Trimmed, length-capped string, or null when it is empty or not a string.
 *  The cap is the real point — an unbounded field is a way to fill a database
 *  and to blow up an email body. */
function str(value: unknown, max: number): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed || trimmed.length > max) return null;
  return trimmed;
}

/** Deliberately loose. Address validation by regular expression is a trap —
 *  the grammar allows far more than any short pattern admits, and the only
 *  real proof an address works is mail arriving at it. This rejects the
 *  obviously-not-an-address cases and leaves the rest to delivery. */
function email(value: unknown): string | null {
  const candidate = str(value, 254);
  if (!candidate) return null;
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(candidate) ? candidate : null;
}

/* ---------------------------------------------------------------- counters */

async function visitors(request: Request, env: Env): Promise<Response> {
  // POST counts this browser once (the localStorage dedupe lives in
  // components/sections/VisitorCounter.tsx); everything else just reads.
  const write = request.method === "POST";
  if (!write && request.method !== "GET" && request.method !== "HEAD") {
    return fail(new Error("Method not allowed"), 405);
  }

  if (env.KV) {
    try {
      const current = Number((await env.KV.get(VISITOR_KEY)) ?? 0);
      const next = write ? current + 1 : current;
      if (write) await env.KV.put(VISITOR_KEY, String(next));
      return json({ ok: true, data: { count: next } });
    } catch (error) {
      return fail(error);
    }
  }

  return upstash(write ? "incr" : "get", env);
}

/** The pre-KV counter. Kept only until the KV namespace is bound, so the live
 *  count survives the move instead of restarting at one. */
async function upstash(command: "get" | "incr", env: Env): Promise<Response> {
  const { UPSTASH_REDIS_REST_URL: url, UPSTASH_REDIS_REST_TOKEN: token } = env;
  if (!url || !token) {
    return fail(new Error("No counter store configured (KV or Upstash)"));
  }

  try {
    const res = await fetch(`${url}/${command}/${VISITOR_KEY}`, {
      headers: { Authorization: `Bearer ${token}`, Accept: "application/json" },
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
    if (!res.ok) return fail(new Error(`Upstash returned ${res.status}`));
    const { result } = (await res.json()) as { result: number | string | null };
    return json({ ok: true, data: { count: Number(result ?? 0) } });
  } catch (error) {
    return fail(error);
  }
}

/** SHA-256 of IP + slug + today, used as the dedupe key.
 *
 *  The hash is what keeps this from being tracking: it is one-way, it is salted
 *  by the slug and the date, and it expires in 24 hours. Nothing that could
 *  identify a person is ever written down — only the fact that *some* browser
 *  already counted this post today. */
async function viewerKey(ip: string, slug: string): Promise<string> {
  const day = new Date().toISOString().slice(0, 10);
  const bytes = new TextEncoder().encode(`${ip}:${slug}:${day}`);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  const hex = [...new Uint8Array(digest)]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
  return `seen:${hex}`;
}

async function recordView(
  request: Request,
  env: Env,
  slug: string,
): Promise<Response> {
  if (request.method !== "POST") {
    return fail(new Error("Method not allowed"), 405);
  }
  if (!env.KV) return fail(new Error("View counter not configured"));
  // Slugs come from the URL, so they are cheap to forge. Bound the character
  // set and the length before either one becomes a KV key.
  if (!/^[a-z0-9-]{1,120}$/i.test(slug)) {
    return fail(new Error("Invalid slug"), 400);
  }
  if (await rateLimited(env, request, "views")) {
    return fail(new Error("Too many requests"), 429);
  }

  try {
    const dedupe = await viewerKey(clientIp(request), slug);
    if (await env.KV.get(dedupe)) {
      // Already counted today. Report the current number rather than an error:
      // the caller asked to record a read, and the read is recorded.
      const count = Number((await env.KV.get(`${VIEW_PREFIX}${slug}`)) ?? 0);
      return json({ ok: true, data: { count, counted: false } });
    }

    const count = Number((await env.KV.get(`${VIEW_PREFIX}${slug}`)) ?? 0) + 1;
    await env.KV.put(`${VIEW_PREFIX}${slug}`, String(count));
    await env.KV.put(dedupe, "1", { expirationTtl: 60 * 60 * 24 });
    return json({ ok: true, data: { count, counted: true } });
  } catch (error) {
    return fail(error);
  }
}

async function allViews(env: Env): Promise<Response> {
  if (!env.KV) return fail(new Error("View counter not configured"));
  try {
    const counts: Record<string, number> = {};
    // Annotated rather than inferred: `cursor` is assigned from `page` and
    // `page` is produced using `cursor`, which TypeScript reads as circular.
    let cursor: string | undefined;
    let page: KVNamespaceListResult<unknown, string>;

    // KV list() is paginated. A portfolio will never fill one page, but a loop
    // that silently truncates is the kind of bug nobody notices for a year.
    do {
      page = await env.KV.list({ prefix: VIEW_PREFIX, cursor });
      for (const key of page.keys) {
        const slug = key.name.slice(VIEW_PREFIX.length);
        counts[slug] = Number((await env.KV.get(key.name)) ?? 0);
      }
      cursor = page.list_complete ? undefined : page.cursor;
    } while (cursor);

    return json({ ok: true, data: counts });
  } catch (error) {
    return fail(error);
  }
}

/* ------------------------------------------------------------------- forms */

async function contact(request: Request, env: Env): Promise<Response> {
  if (request.method !== "POST") {
    return fail(new Error("Method not allowed"), 405);
  }
  if (!sameOrigin(request)) return fail(new Error("Forbidden"), 403);
  if (await rateLimited(env, request, "contact")) {
    return fail(new Error("Too many messages. Try again in a minute."), 429);
  }

  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return fail(new Error("Expected JSON"), 400);
  }

  const name = str(body.name, 120);
  const from = email(body.email);
  const subject = str(body.subject, 120);
  const message = str(body.message, 5000);

  if (!name || !from || !subject || !message) {
    return fail(new Error("Please fill in every field."), 400);
  }

  if (!(await verifyTurnstile(env, String(body.token ?? ""), clientIp(request)))) {
    return fail(new Error("Bot check failed. Reload and try again."), 400);
  }

  // The database write happens FIRST and its failure is the only one that can
  // fail the request. A Resend outage must never lose a message — if the row is
  // safe, the submission succeeded, and the email is a convenience on top.
  if (env.DB) {
    try {
      await env.DB.prepare(
        "INSERT INTO contact_messages (name, email, subject, message) VALUES (?, ?, ?, ?)",
      )
        .bind(name, from, subject, message)
        .run();
    } catch (error) {
      return fail(error);
    }
  } else if (!env.RESEND_API_KEY) {
    // No database and no mailer: the message would go nowhere. Say so rather
    // than returning a success the visitor would believe.
    return fail(new Error("Contact form is not configured yet."));
  }

  const emailed = await sendEmail(env, { name, from, subject, message });

  return json({
    ok: true,
    data: {
      stored: Boolean(env.DB),
      // Surfaced so /views-style debugging does not need log access. The
      // visitor is told "sent" either way, because for them it was.
      emailed,
    },
  });
}

async function sendEmail(
  env: Env,
  msg: { name: string; from: string; subject: string; message: string },
): Promise<boolean> {
  if (!env.RESEND_API_KEY || !env.CONTACT_TO_EMAIL) return false;

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        authorization: `Bearer ${env.RESEND_API_KEY}`,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        // Resend's shared sender, which needs no verified domain. Swap it for
        // your own address once a domain is verified.
        from: "Portfolio <onboarding@resend.dev>",
        to: [env.CONTACT_TO_EMAIL],
        // Replying goes to the person who wrote in, not to the sender address.
        reply_to: msg.from,
        subject: `[portfolio] ${msg.subject} — ${msg.name}`,
        text: `From: ${msg.name} <${msg.from}>\nSubject: ${msg.subject}\n\n${msg.message}`,
      }),
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
    return res.ok;
  } catch {
    return false;
  }
}

async function newsletter(request: Request, env: Env): Promise<Response> {
  if (request.method !== "POST") {
    return fail(new Error("Method not allowed"), 405);
  }
  if (!sameOrigin(request)) return fail(new Error("Forbidden"), 403);
  if (await rateLimited(env, request, "newsletter")) {
    return fail(new Error("Too many attempts. Try again in a minute."), 429);
  }
  if (!env.DB) return fail(new Error("Newsletter is not configured yet."));

  let body: Record<string, unknown>;
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    return fail(new Error("Expected JSON"), 400);
  }

  const address = email(body.email);
  if (!address) return fail(new Error("That email doesn't look right."), 400);

  if (!(await verifyTurnstile(env, String(body.token ?? ""), clientIp(request)))) {
    return fail(new Error("Bot check failed. Reload and try again."), 400);
  }

  try {
    // OR IGNORE against the UNIQUE column: signing up twice is a silent
    // success, not an error the visitor has to interpret.
    await env.DB.prepare(
      "INSERT OR IGNORE INTO newsletter_subscribers (email) VALUES (?)",
    )
      .bind(address)
      .run();
    return json({ ok: true, data: { subscribed: true } });
  } catch (error) {
    return fail(error);
  }
}

/* ----------------------------------------------------------------- routing */

const handler = {
  async fetch(request: Request, env: Env): Promise<Response> {
    const { pathname } = new URL(request.url);

    // Exact matches only, so no other path can reach a binding or a secret.
    if (pathname === "/api/visitors") return visitors(request, env);
    if (pathname === "/api/blog-views") return allViews(env);
    if (pathname === "/api/contact") return contact(request, env);
    if (pathname === "/api/newsletter") return newsletter(request, env);

    // The one prefixed route. The slug is validated inside recordView.
    if (pathname.startsWith("/api/blog-views/")) {
      return recordView(
        request,
        env,
        decodeURIComponent(pathname.slice("/api/blog-views/".length)),
      );
    }

    return env.ASSETS.fetch(request);
  },
};

export default handler;
